version: "3.9"

services:
  jottery:
    image: ghcr.io/seesee/jottery:latest
    container_name: jottery
    ports:
      - "8088:8088"
    volumes:
      - jottery_data:/app/data
    restart: unless-stopped

volumes:
  jottery_data:
